config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  get '/feed', to: 'posts#feed'
  get '/reblog/:id', to: 'posts#reblog'
  patch '/reblog', to: 'posts#post_reblog'
  devise_for :users
  root 'application#index'
  
  resources :users
  get '/discover', to: 'users#discover'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  get '/preferences', to: 'application#preferences'
  resources :relationships, only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    
    #paperclip for photo posts
    has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
     belongs_to :follower, class_name: "User"
     belongs_to :followed, class_name: "User"
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #paperclip for avatar
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "default_avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  has_many :posts
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
                                  
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
                                   
  has_many :following, through: :active_relationships,  source: :followed
  
  has_many :followers, through: :passive_relationships, source: :follower
   
  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def index
    if user_signed_in?
      redirect_to feed_path
    end
  end

  def preferences
    @user = current_user
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def index
        if !current_user
            redirect_to new_user_session_path
        end
       @posts = Post.all.sort_by { |a| [ a.created_at ] }.reverse!
       @top_blogs = User.all.sort_by { |a| [a.posts.count] }
    end
    
    def feed
        if !current_user
            redirect_to new_user_session_path
        end
       @posts = []
       @following = current_user.following
       
       #loop to get all posts from each user (loop by @following),
       #adding each users posts to @posts
       
       @following.each do |user|
          @posts =  @posts + user.posts 
       end
       
       #add users own posts
       @posts = @posts + current_user.posts
       
       #sort @posts by date
       @posts = @posts.sort_by { |a| [ a.created_at ] }.reverse!
    end
    
    def new 
        if !current_user
            redirect_to new_user_session_path
        end
        @post = Post.new
        @following = current_user.following
    end
    
    def create
       @post = Post.new(post_params) 
       @post.user = current_user
       @post.source = current_user.id
       if @post.save
          redirect_to @post 
       end
    end
    
    def show
       @post = Post.find(params[:id]) 
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        redirect_to post_path(@post)
    end
    
    def reblog
       @post = Post.find(params[:id]) 
    end
    
    def post_reblog
        @post = Post.new(post_params) 
        @post.user = current_user
        @post.source = params[:source]
        @post.photo = Post.find(params[:photo_id]).photo
        @post.reblogged_from = params[:reblogged_from]
        if @post.save
          redirect_to feed_path 
        end
    end
   
   
private
   def post_params
    params.require(:post).permit(:title, :body, :source, :photo_id)
   end
    
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    
    def create
        user = User.find(params[:followed_id])
        current_user.follow(user)
        redirect_to user
    end

    def destroy
        user = Relationship.find(params[:id]).followed
        current_user.unfollow(user)
        redirect_to user
    end
end
    

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
        @posts = @user.posts
        #sort @posts by date
        @posts = @posts.sort_by { |a| [ a.created_at ] }.reverse!
    end
    
    def following
       @following = current_user.following 
    end
    
    def followers
       @followers = current_user.followers 
    end
    
    def discover
        @top_blogs = User.all.sort_by { |a| [a.posts.count] }
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationshipscontroller_helper.rb
module RelationshipscontrollerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-8 center white'>
        <br><br><br>
        <h1 class="bookman">Rumblr.</h1>
        <br>
        <% if !user_signed_in? %>
        <%= link_to "Log in", new_user_session_path, class:"white"%> or <%= link_to "Sign up", new_user_registration_path, class:"white" %>
        <% else %>
        You are now signed in :) 
        <% end %>
    </div>
    <div class='col-md-2'></div>
</div>

app/views/application/preferences.html.erb
<div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-6'>
        <h1 class='white'>Preferences</h1>
    </div>
    <div class='col-md-3'>

    </div>
    <div class='col-md-1'></div>
</div>

app/views/forms/_post.html.erb
<div class="post_card" style="min-height: 400px">
    <span style="color:black;">
        <h1 class="tumblr_blue center sidebar_header">New Post</h1>
        <%= form_for @post, html: { multipart: true } do |f| %>
        <%= f.text_field :title, size: "15x1", placeholder:"Title", style:"font-size:50px; border: 0px solid;", autocomplete:"off"  %><br>
        <%= f.text_area :body, size: "60x2", placeholder:"Your text here", style:"border: 0px solid;", autocomplete:"off" %>
        <%= f.file_field :photo, style:"padding-left:40%;" %>
        <button type="button submit" name="commit" class="btn btn-secondary">Create Post</button>
    <% end %>
    </span>
</div>

app/views/forms/_reblog.html.erb
<span style="color:black;">
<%= form_for @post, :url => { :action => "post_reblog", method: "POST"} do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>
    <%= f.label :body %><br>
    <%= f.text_area :body, size: "45x6" %><br>
    <%= hidden_field_tag :reblogged_from, @post.user.id %>
    <%= hidden_field_tag :source, @post.source %>
    <%= hidden_field_tag :photo_id, @post.id %>
    <%= f.submit%>
<% end %>
</span>

app/views/layouts/_discover_side_panel.html.erb
<div class="following_container">
            <div class="center dark_bottom_border">
                <%= link_to feed_path do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">home</i>
                <% end %>
                <%= link_to discover_path do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">explore</i>
                <% end %>
                <%= link_to new_post_path do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">mode_edit</i>
                <% end %>
                <%= link_to current_user do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">face</i>
                <% end %>
            </div>
            <h2 class="light_gray sidebar_header">Discover</h2>
            <h5 class="light_gray">Recommended blogs:</h5>
            <% @top_blogs.each do |user| %>
            <div>
                <a href="<%= user_path(user) %>">
                    <%= image_tag user.avatar.url, class:"avatar_small" %>
                </a>
                <%= link_to user.username, user, class: "med_gray" %>
            </div>
            <% end %>
 </div>

app/views/layouts/_side_panel.html.erb
<div class="following_container">
            <div class="center dark_bottom_border">
                <%= link_to feed_path do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">home</i>
                <% end %>
                <%= link_to discover_path do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">explore</i>
                <% end %>
                <%= link_to new_post_path do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">mode_edit</i>
                <% end %>
                <%= link_to current_user do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">face</i>
                <% end %>
            </div>
            <h2 class="light_gray sidebar_header">Dashboard</h2>
            <h5 class="light_gray">You're following:</h5>
            <% current_user.following.each do |following| %>
            <div>
                <a href="<%= user_path(following) %>">
                    <%= image_tag following.avatar.url, class:"avatar_small" %>
                </a>
                <%= link_to following.username, following, class: "med_gray" %>
            </div>
            <% end %>
 </div>

app/views/layouts/_user_card.html.erb
<div class="post_card">
    <div class='post_header center'>
        <%= image_tag user.avatar.url, class:"avatar" %>
        <%= link_to user.username, user, class:"username" %>  
    </div>
    <div class="post_content cf">
        <br>
        <div class='row'>
            <div class='col-md-4'>
                <% if user.posts[-1] %>
                    <%= link_to user.posts[-1].title, post_path(user.posts[-1]) %>
                    <br>
                    <%= user.posts[-1].body %>
                    <% if user.posts[-1].photo.url != "/photos/original/missing.png" %>
                        <%= image_tag user.posts[-1].photo.url, style:"width: 150px" %>
                    <% end %>
                <% end %>
            </div>
            <div class='col-md-4'>
                <% if user.posts[-2] %>
                    <%= link_to user.posts[-2].title, post_path(user.posts[-2]) %>
                    <br>
                    <%= user.posts[-2].body %>
                    <% if user.posts[-2].photo.url != "/photos/original/missing.png" %>
                        <%= image_tag user.posts[-2].photo.url, style:"width: 150px" %>
                    <% end %>
                <% end %>
            </div>
            <div class='col-md-4'>
                <% if user.posts[-3] %>
                    <%= link_to user.posts[-3].title, post_path(user.posts[-3]) %>
                    <br>
                    <%= user.posts[-3].body %>
                    <% if user.posts[-3].photo.url != "/photos/original/missing.png" %>
                        <%= image_tag user.posts[-3].photo.url, style:"width: 150px" %>
                    <% end %>
                <% end %>
            </div>
        </div>

    </div>
</div>

app/views/layouts/_user_side_panel.html.erb
<div class="following_container">
            <div class="center dark_bottom_border">
                <%= link_to feed_path do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">home</i>
                <% end %>
                <%= link_to discover_path do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">explore</i>
                <% end %>
                <%= link_to new_post_path do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">mode_edit</i>
                <% end %>
                <%= link_to current_user do %>
                    <i class="material-icons light_gray" style="font-size: 35px;">face</i>
                <% end %>
            </div>
            <h2 class="light_gray sidebar_header"><%= @user.username %></h2>
            <!-- follow button -->
            <% if current_user != @user %>
                <% if !current_user.following?(@user) %>
                    <%= form_for(current_user.active_relationships.build) do |f| %>
                    <div><%= hidden_field_tag :followed_id, @user.id %></div>
                    <%= f.submit "Follow", class: "btn btn-primary" %>
                    <% end %>
                <% else %>
                    <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                    html: { method: :delete }) do |f| %>
                    <%= f.submit "Unfollow", class: "btn" %>
                    <% end %>
                <% end %>
            <% end %>
            <!-- end follow button -->
            <br>
            <h5 class="light_gray">Following:</h5>
            <% @user.following.each do |following| %>
            <div>
                <a href="<%= user_path(following) %>">
                    <%= image_tag following.avatar.url, class:"avatar_small" %>
                </a>
                <%= link_to following.username, following, class: "med_gray" %>
            </div>
            <% end %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- BOOTSTRAP -->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- END BOOTSTRAP -->
  
  <!-- google icon font -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  
</head>
<body class="background">
  <nav class="navbar navbar-default">
  <div class="container-fluid background">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand bookman" href="/">Rumblr.</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <!-- SEARCH BAR
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      -->
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %> 
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
        <% if current_user %>
        
        <!-- MENU UP TO SM DEVICES -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <!-- <li><a href="/users">View all users</a></li> -->
              <!-- <li><a href="/preferences">Preferences</a></li> -->
              <li><%= link_to 'Feed', feed_path%></li>
              <li><%= link_to 'Profile', current_user%></li>
              <li><%= link_to 'Discover', discover_path%></li>
              <li><%= link_to 'New Post', new_post_path%></li>
              <li><%= link_to 'Following', following_user_path(current_user)%></li>
              <li><%= link_to 'Followers', followers_user_path(current_user)%></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: 'DELETE' %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class='container-fluid'>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_post.html.erb
<div class="post_card">
    <div class='post_header'>
        <%= image_tag post.user.avatar.url, class:"avatar" %>
        <%= link_to post.user.username, post.user, class:"username" %>  
        <% if post.reblogged_from %>
            <i class="material-icons med_gray">repeat</i>
            <%= link_to User.find(post.reblogged_from).username,  User.find(post.reblogged_from), class:"username"%>
        <% end %>
    </div>
    <div class="post_content cf">
        <h2><%= post.title %></h2>
        <% if post.photo.url != "/photos/original/missing.png" %>
            <%= image_tag post.photo.url, class:"photo_post"%>
        <% end %>
        <h4><%= post.body %></h4>
        <span class="med_gray">source: <%= link_to User.find(post.source).username, User.find(post.source), class:"med_gray"%></span>
        
        <!-- timestamp, not currently visible -->
        <% post.created_at.strftime("%I:%M %p %Z on %m-%d-%Y") %>
        <div style="float:right;">
            <% if post.user == current_user %>
                <%= link_to post_path(post), method:"DELETE" do %>
                    <i class="material-icons med_gray">delete</i>
                <% end %>
                <%= link_to edit_post_path(post) do %>
                    <i class="material-icons med_gray">mode_edit</i>
                <% end %>
            <% end %>
            <%= link_to "/reblog/" + post.id.to_s do %>
                    <i class="material-icons med_gray">repeat</i>
                <% end %>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-8 center white'>
        <h1>Edit Post</h1>
        <%= render "forms/post" %>
    </div>
    <div class='col-md-2'></div>
</div>

app/views/posts/feed.html.erb
<div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-6'>
        <% @posts.each do |post|%>
            <%= render partial: "post", locals: {post: post} %>
        <% end %>
    </div>
    <div class='col-md-3 hidden-xs hidden-sm'>
        <%= render partial: "layouts/side_panel"%>
    </div>
    <div class='col-md-1'></div>
</div>

app/views/posts/index.html.erb
<div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-6'>
        <% @posts.each do |post|%>
            <%= render partial: "post", locals: {post: post} %>
        <% end %>
    </div>
    <div class='col-md-3'>
        <%= render partial: "layouts/discover_side_panel" %>
    </div>
    <div class='col-md-1'></div>
</div>

app/views/posts/new.html.erb
<div class='row' style="height:90vh">
    <div class='col-md-2'></div>
    <div class='col-md-6'>
        <%= render "forms/post" %>
    </div>
    <div class='col-md-3 hidden-xs hidden-sm'>
        <%= render partial: "layouts/side_panel" %>
    </div>
    <div class='col-md-1'></div>
</div>

app/views/posts/reblog.html.erb
<div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-8 center white'>
        <h1>Reblog</h1>
        <%= render "forms/reblog" %>
    </div>
    <div class='col-md-2'></div>
</div>

app/views/posts/show.html.erb
<div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-8'>
        <%= render partial: "post", locals: {post: @post} %>
    </div>
    <div class='col-md-2'></div>
</div>

app/views/users/discover.html.erb
<div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-6'>
        <% @top_blogs.each do |user| %>
            <%= render partial: 'layouts/user_card', locals: {user: user}%>
        <% end %>
    </div>
    <div class='col-md-3 hidden-xs hidden-sm'>
        <%= render partial: "layouts/discover_side_panel" %>
    </div>
    <div class='col-md-1'></div>
</div>

app/views/users/followers.html.erb
<div class='row'>
    <div class='col-xs-2'></div>
    <div class='col-xs-8 white'>
        <h1>Followers:</h1>
        
        <% @followers.each do |follower_user|%>
            <%= link_to follower_user.username, follower_user %> <br>
        <% end %>
    </div>
    <div class='col-xs-2'></div>
</div>

app/views/users/following.html.erb
<div class='row'>
    <div class='col-xs-2'></div>
    <div class='col-xs-8 white'>
        <h1>Following:</h1>
        
        <% @following.each do |following_user|%>
            <%= link_to following_user.username, following_user %> <br>
        <% end %>
    </div>
    <div class='col-xs-2'></div>
</div>

app/views/users/index.html.erb
<div class="white">
    <% @users.each do |user| %>
        <%= link_to user.email, user %><br>
    <%end%>
</div>

app/views/users/show.html.erb
    
<div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-6'>
        <% @posts.each do |post|%>
            <%= render partial: "posts/post", locals: {post: post, user: @user} %>
        <% end %>
    </div>
    <div class='col-md-3 hidden-xs hidden-sm'>
        <%= render partial: "layouts/user_side_panel"%>
    </div>
    <div class='col-md-1'></div>
</div>
    
</div>